import { PrismaClient } from '@prisma/client';
import { faker } from '@faker-js/faker';

const run = async () => {
  const prisma = new PrismaClient();
  try {
    if ((await prisma.language.count()) === 0) {
      await prisma.language.createMany({
        data: [
          {
            name: 'Español',
          },
          {
            name: 'English',
          },
        ],
      });
      console.log('Languages created');
    } else {
      console.log('Default languages already created');
    }
    if ((await prisma.categories.count()) === 0) {
      await prisma.categories.createMany({
        data: [
          {
            name: 'Electronics',
            description: 'Electronics',
          },
          {
            name: 'Sports',
            description: 'Sports',
          },
        ],
      });
      console.log('Categories created');
    } else {
      console.log('Default categories already created');
    }
    if ((await prisma.currency.count()) === 0) {
      await prisma.currency.createMany({
        data: [
          {
            id: 1,
            name: 'US Dollars',
            abbrev: 'USD',
            symbol: '$',
          },
          {
            id: 2,
            name: 'Mexican Pesos',
            abbrev: 'MXN',
            symbol: '$',
          },
          {
            id: 3,
            name: 'EURO',
            abbrev: 'EUR',
            symbol: '€',
          },
        ],
      });
      console.log('Currencies created');
    } else {
      console.log('Default currencies already created');
    }
    if ((await prisma.countries.count()) === 0) {
      await prisma.countries.createMany({
        data: [
          {
            id: 1,
            country_code: 'AF',
            name: 'Afghanistan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 2,
            country_code: 'AX',
            name: 'Åland Islands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 3,
            country_code: 'AL',
            name: 'Albania',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 4,
            country_code: 'DZ',
            name: 'Algeria',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 5,
            country_code: 'AS',
            name: 'American Samoa',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 6,
            country_code: 'AD',
            name: 'Andorra',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 7,
            country_code: 'AO',
            name: 'Angola',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 8,
            country_code: 'AI',
            name: 'Anguilla',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 9,
            country_code: 'AQ',
            name: 'Antarctica',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 10,
            country_code: 'AG',
            name: 'Antigua and Barbuda',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 11,
            country_code: 'AR',
            name: 'Argentina',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 12,
            country_code: 'AM',
            name: 'Armenia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 13,
            country_code: 'AW',
            name: 'Aruba',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 14,
            country_code: 'AU',
            name: 'Australia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 15,
            country_code: 'AT',
            name: 'Austria',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 16,
            country_code: 'AZ',
            name: 'Azerbaijan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 17,
            country_code: 'BS',
            name: 'Bahamas',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 18,
            country_code: 'BH',
            name: 'Bahrain',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 19,
            country_code: 'BD',
            name: 'Bangladesh',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 20,
            country_code: 'BB',
            name: 'Barbados',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 21,
            country_code: 'BY',
            name: 'Belarus',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 22,
            country_code: 'BE',
            name: 'Belgium',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 23,
            country_code: 'BZ',
            name: 'Belize',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 24,
            country_code: 'BJ',
            name: 'Benin',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 25,
            country_code: 'BM',
            name: 'Bermuda',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 26,
            country_code: 'BT',
            name: 'Bhutan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 27,
            country_code: 'BO',
            name: 'Bolivia (Plurinational State of)',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 28,
            country_code: 'BQ',
            name: 'Bonaire, Sint Eustatius and Saba',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 29,
            country_code: 'BA',
            name: 'Bosnia and Herzegovina',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 30,
            country_code: 'BW',
            name: 'Botswana',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 31,
            country_code: 'BV',
            name: 'Bouvet Island',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 32,
            country_code: 'BR',
            name: 'Brazil',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 33,
            country_code: 'IO',
            name: 'British Indian Ocean Territory',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 34,
            country_code: 'BN',
            name: 'Brunei Darussalam',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 35,
            country_code: 'BG',
            name: 'Bulgaria',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 36,
            country_code: 'BF',
            name: 'Burkina Faso',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 37,
            country_code: 'BI',
            name: 'Burundi',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 38,
            country_code: 'CV',
            name: 'Cabo Verde',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 39,
            country_code: 'KH',
            name: 'Cambodia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 40,
            country_code: 'CM',
            name: 'Cameroon',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 41,
            country_code: 'CA',
            name: 'Canada',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 42,
            country_code: 'KY',
            name: 'Cayman Islands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 43,
            country_code: 'CF',
            name: 'Central African Republic',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 44,
            country_code: 'TD',
            name: 'Chad',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 45,
            country_code: 'CL',
            name: 'Chile',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 46,
            country_code: 'CN',
            name: 'China',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 47,
            country_code: 'CX',
            name: 'Christmas Island',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 48,
            country_code: 'CC',
            name: 'Cocos (Keeling) Islands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 49,
            country_code: 'CO',
            name: 'Colombia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 50,
            country_code: 'KM',
            name: 'Comoros',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 51,
            country_code: 'CG',
            name: 'Congo',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 52,
            country_code: 'CD',
            name: 'Congo (Democratic Republic of the)',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 53,
            country_code: 'CK',
            name: 'Cook Islands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 54,
            country_code: 'CR',
            name: 'Costa Rica',
            id_currency: 2,
            id_language: 1,
          },
          {
            id: 55,
            country_code: 'CI',
            name: "'Côte d'Ivoire'",
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 56,
            country_code: 'HR',
            name: 'Croatia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 57,
            country_code: 'CU',
            name: 'Cuba',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 58,
            country_code: 'CW',
            name: 'Curaçao',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 59,
            country_code: 'CY',
            name: 'Cyprus',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 60,
            country_code: 'CZ',
            name: 'Czechia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 61,
            country_code: 'DK',
            name: 'Denmark',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 62,
            country_code: 'DJ',
            name: 'Djibouti',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 63,
            country_code: 'DM',
            name: 'Dominica',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 64,
            country_code: 'DO',
            name: 'Dominican Republic',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 65,
            country_code: 'EC',
            name: 'Ecuador',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 66,
            country_code: 'EG',
            name: 'Egypt',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 67,
            country_code: 'SV',
            name: 'El Salvador',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 68,
            country_code: 'GQ',
            name: 'Equatorial Guinea',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 69,
            country_code: 'ER',
            name: 'Eritrea',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 70,
            country_code: 'EE',
            name: 'Estonia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 71,
            country_code: 'ET',
            name: 'Ethiopia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 72,
            country_code: 'FK',
            name: 'Falkland Islands (Malvinas)',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 73,
            country_code: 'FO',
            name: 'Faroe Islands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 74,
            country_code: 'FJ',
            name: 'Fiji',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 75,
            country_code: 'FI',
            name: 'Finland',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 76,
            country_code: 'FR',
            name: 'France',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 77,
            country_code: 'GF',
            name: 'French Guiana',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 78,
            country_code: 'PF',
            name: 'French Polynesia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 79,
            country_code: 'TF',
            name: 'French Southern Territories',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 80,
            country_code: 'GA',
            name: 'Gabon',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 81,
            country_code: 'GM',
            name: 'Gambia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 82,
            country_code: 'GE',
            name: 'Georgia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 83,
            country_code: 'DE',
            name: 'Germany',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 84,
            country_code: 'GH',
            name: 'Ghana',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 85,
            country_code: 'GI',
            name: 'Gibraltar',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 86,
            country_code: 'GR',
            name: 'Greece',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 87,
            country_code: 'GL',
            name: 'Greenland',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 88,
            country_code: 'GD',
            name: 'Grenada',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 89,
            country_code: 'GP',
            name: 'Guadeloupe',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 90,
            country_code: 'GU',
            name: 'Guam',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 91,
            country_code: 'GT',
            name: 'Guatemala',
            id_currency: 2,
            id_language: 1,
          },
          {
            id: 92,
            country_code: 'GG',
            name: 'Guernsey',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 93,
            country_code: 'GN',
            name: 'Guinea',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 94,
            country_code: 'GW',
            name: 'Guinea-Bissau',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 95,
            country_code: 'GY',
            name: 'Guyana',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 96,
            country_code: 'HT',
            name: 'Haiti',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 97,
            country_code: 'HM',
            name: 'Heard Island and McDonald Islands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 98,
            country_code: 'VA',
            name: 'Holy See',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 99,
            country_code: 'HN',
            name: 'Honduras',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 100,
            country_code: 'HK',
            name: 'Hong Kong',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 101,
            country_code: 'HU',
            name: 'Hungary',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 102,
            country_code: 'IS',
            name: 'Iceland',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 103,
            country_code: 'IN',
            name: 'India',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 104,
            country_code: 'ID',
            name: 'Indonesia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 105,
            country_code: 'IR',
            name: 'Iran (Islamic Republic of)',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 106,
            country_code: 'IQ',
            name: 'Iraq',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 107,
            country_code: 'IE',
            name: 'Ireland',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 108,
            country_code: 'IM',
            name: 'Isle of Man',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 109,
            country_code: 'IL',
            name: 'Israel',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 110,
            country_code: 'IT',
            name: 'Italy',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 111,
            country_code: 'JM',
            name: 'Jamaica',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 112,
            country_code: 'JP',
            name: 'Japan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 113,
            country_code: 'JE',
            name: 'Jersey',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 114,
            country_code: 'JO',
            name: 'Jordan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 115,
            country_code: 'KZ',
            name: 'Kazakhstan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 116,
            country_code: 'KE',
            name: 'Kenya',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 117,
            country_code: 'KI',
            name: 'Kiribati',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 118,
            country_code: 'KP',
            name: "'Korea (Democratic People's Republic of)'",
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 119,
            country_code: 'KR',
            name: 'Korea (Republic of)',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 120,
            country_code: 'KW',
            name: 'Kuwait',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 121,
            country_code: 'KG',
            name: 'Kyrgyzstan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 122,
            country_code: 'LA',
            name: "'Lao People's Democratic Republic'",
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 123,
            country_code: 'LV',
            name: 'Latvia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 124,
            country_code: 'LB',
            name: 'Lebanon',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 125,
            country_code: 'LS',
            name: 'Lesotho',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 126,
            country_code: 'LR',
            name: 'Liberia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 127,
            country_code: 'LY',
            name: 'Libya',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 128,
            country_code: 'LI',
            name: 'Liechtenstein',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 129,
            country_code: 'LT',
            name: 'Lithuania',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 130,
            country_code: 'LU',
            name: 'Luxembourg',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 131,
            country_code: 'MO',
            name: 'Macao',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 132,
            country_code: 'MK',
            name: 'North Macedonia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 133,
            country_code: 'MG',
            name: 'Madagascar',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 134,
            country_code: 'MW',
            name: 'Malawi',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 135,
            country_code: 'MY',
            name: 'Malaysia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 136,
            country_code: 'MV',
            name: 'Maldives',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 137,
            country_code: 'ML',
            name: 'Mali',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 138,
            country_code: 'MT',
            name: 'Malta',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 139,
            country_code: 'MH',
            name: 'Marshall Islands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 140,
            country_code: 'MQ',
            name: 'Martinique',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 141,
            country_code: 'MR',
            name: 'Mauritania',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 142,
            country_code: 'MU',
            name: 'Mauritius',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 143,
            country_code: 'YT',
            name: 'Mayotte',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 144,
            country_code: 'MX',
            name: 'Mexico',
            id_currency: 2,
            id_language: 1,
          },
          {
            id: 145,
            country_code: 'FM',
            name: 'Micronesia (Federated States of)',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 146,
            country_code: 'MD',
            name: 'Moldova (Republic of)',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 147,
            country_code: 'MC',
            name: 'Monaco',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 148,
            country_code: 'MN',
            name: 'Mongolia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 149,
            country_code: 'ME',
            name: 'Montenegro',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 150,
            country_code: 'MS',
            name: 'Montserrat',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 151,
            country_code: 'MA',
            name: 'Morocco',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 152,
            country_code: 'MZ',
            name: 'Mozambique',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 153,
            country_code: 'MM',
            name: 'Myanmar',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 154,
            country_code: 'NA',
            name: 'Namibia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 155,
            country_code: 'NR',
            name: 'Nauru',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 156,
            country_code: 'NP',
            name: 'Nepal',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 157,
            country_code: 'NL',
            name: 'Netherlands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 158,
            country_code: 'NC',
            name: 'New Caledonia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 159,
            country_code: 'NZ',
            name: 'New Zealand',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 160,
            country_code: 'NI',
            name: 'Nicaragua',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 161,
            country_code: 'NE',
            name: 'Niger',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 162,
            country_code: 'NG',
            name: 'Nigeria',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 163,
            country_code: 'NU',
            name: 'Niue',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 164,
            country_code: 'NF',
            name: 'Norfolk Island',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 165,
            country_code: 'MP',
            name: 'Northern Mariana Islands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 166,
            country_code: 'NO',
            name: 'Norway',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 167,
            country_code: 'OM',
            name: 'Oman',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 168,
            country_code: 'PK',
            name: 'Pakistan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 169,
            country_code: 'PW',
            name: 'Palau',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 170,
            country_code: 'PS',
            name: 'Palestine, State of',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 171,
            country_code: 'PA',
            name: 'Panama',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 172,
            country_code: 'PG',
            name: 'Papua New Guinea',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 173,
            country_code: 'PY',
            name: 'Paraguay',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 174,
            country_code: 'PE',
            name: 'Peru',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 175,
            country_code: 'PH',
            name: 'Philippines',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 176,
            country_code: 'PN',
            name: 'Pitcairn',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 177,
            country_code: 'PL',
            name: 'Poland',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 178,
            country_code: 'PT',
            name: 'Portugal',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 179,
            country_code: 'PR',
            name: 'Puerto Rico',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 180,
            country_code: 'QA',
            name: 'Qatar',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 181,
            country_code: 'RE',
            name: 'Réunion',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 182,
            country_code: 'RO',
            name: 'Romania',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 183,
            country_code: 'RU',
            name: 'Russian Federation',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 184,
            country_code: 'RW',
            name: 'Rwanda',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 185,
            country_code: 'BL',
            name: 'Saint Barthélemy',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 186,
            country_code: 'SH',
            name: 'Saint Helena, Ascension and Tristan da Cunha',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 187,
            country_code: 'KN',
            name: 'Saint Kitts and Nevis',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 188,
            country_code: 'LC',
            name: 'Saint Lucia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 189,
            country_code: 'MF',
            name: 'Saint Martin (French part)',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 190,
            country_code: 'PM',
            name: 'Saint Pierre and Miquelon',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 191,
            country_code: 'VC',
            name: 'Saint Vincent and the Grenadines',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 192,
            country_code: 'WS',
            name: 'Samoa',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 193,
            country_code: 'SM',
            name: 'San Marino',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 194,
            country_code: 'ST',
            name: 'Sao Tome and Principe',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 195,
            country_code: 'SA',
            name: 'Saudi Arabia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 196,
            country_code: 'SN',
            name: 'Senegal',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 197,
            country_code: 'RS',
            name: 'Serbia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 198,
            country_code: 'SC',
            name: 'Seychelles',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 199,
            country_code: 'SL',
            name: 'Sierra Leone',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 200,
            country_code: 'SG',
            name: 'Singapore',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 201,
            country_code: 'SX',
            name: 'Sint Maarten (Dutch part)',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 202,
            country_code: 'SK',
            name: 'Slovakia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 203,
            country_code: 'SI',
            name: 'Slovenia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 204,
            country_code: 'SB',
            name: 'Solomon Islands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 205,
            country_code: 'SO',
            name: 'Somalia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 206,
            country_code: 'ZA',
            name: 'South Africa',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 207,
            country_code: 'GS',
            name: 'South Georgia and the South Sandwich Islands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 208,
            country_code: 'SS',
            name: 'South Sudan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 209,
            country_code: 'ES',
            name: 'Spain',
            id_currency: 3,
            id_language: 1,
          },
          {
            id: 210,
            country_code: 'LK',
            name: 'Sri Lanka',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 211,
            country_code: 'SD',
            name: 'Sudan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 212,
            country_code: 'SR',
            name: 'Suriname',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 213,
            country_code: 'SJ',
            name: 'Svalbard and Jan Mayen',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 214,
            country_code: 'SZ',
            name: 'Eswatini',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 215,
            country_code: 'SE',
            name: 'Sweden',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 216,
            country_code: 'CH',
            name: 'Switzerland',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 217,
            country_code: 'SY',
            name: 'Syrian Arab Republic',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 218,
            country_code: 'TW',
            name: 'Taiwan, Province of China[a]',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 219,
            country_code: 'TJ',
            name: 'Tajikistan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 220,
            country_code: 'TZ',
            name: 'Tanzania, United Republic of',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 221,
            country_code: 'TH',
            name: 'Thailand',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 222,
            country_code: 'TL',
            name: 'Timor-Leste',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 223,
            country_code: 'TG',
            name: 'Togo',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 224,
            country_code: 'TK',
            name: 'Tokelau',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 225,
            country_code: 'TO',
            name: 'Tonga',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 226,
            country_code: 'TT',
            name: 'Trinidad and Tobago',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 227,
            country_code: 'TN',
            name: 'Tunisia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 228,
            country_code: 'TR',
            name: 'Turkey',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 229,
            country_code: 'TM',
            name: 'Turkmenistan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 230,
            country_code: 'TC',
            name: 'Turks and Caicos Islands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 231,
            country_code: 'TV',
            name: 'Tuvalu',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 232,
            country_code: 'UG',
            name: 'Uganda',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 233,
            country_code: 'UA',
            name: 'Ukraine',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 234,
            country_code: 'AE',
            name: 'United Arab Emirates',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 235,
            country_code: 'GB',
            name: 'United Kingdom of Great Britain and Northern Ireland',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 236,
            country_code: 'US',
            name: 'United States of America',
            id_currency: 1,
            id_language: 2,
          },
          {
            id: 237,
            country_code: 'UM',
            name: 'United States Minor Outlying Islands',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 238,
            country_code: 'UY',
            name: 'Uruguay',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 239,
            country_code: 'UZ',
            name: 'Uzbekistan',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 240,
            country_code: 'VU',
            name: 'Vanuatu',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 241,
            country_code: 'VE',
            name: 'Venezuela (Bolivarian Republic of)',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 242,
            country_code: 'VN',
            name: 'Viet Nam',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 243,
            country_code: 'VG',
            name: 'Virgin Islands (British)',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 244,
            country_code: 'VI',
            name: 'Virgin Islands (U.S.)',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 245,
            country_code: 'WF',
            name: 'Wallis and Futuna',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 246,
            country_code: 'EH',
            name: 'Western Sahara',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 247,
            country_code: 'YE',
            name: 'Yemen',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 248,
            country_code: 'ZM',
            name: 'Zambia',
            id_currency: 1,
            id_language: 1,
          },
          {
            id: 249,
            country_code: 'ZW',
            name: 'Zimbabwe',
            id_currency: 1,
            id_language: 1,
          },
        ],
      });
      console.log('Countries created');
    } else {
      console.log('Default countries already created');
    }
    if ((await prisma.store.count()) === 0) {
      await prisma.store.create({
        data: {
          email: 'store@store.com',
          id_default_currency: 1,
          id_default_language: 2,
          name: 'store name',
        },
      });
      console.log('Store created');
    } else {
      console.log('Default store already created');
    }
    if ((await prisma.products.count()) === 0) {
      const countries = [236, 144, 67, 174, 41]; // USA, MEX, SV, PE, CA

      for (let i = 0; i < 150; i++) {
        await prisma.products.create({
          data: {
            name: faker.commerce.product(),
            sku: faker.commerce.productAdjective(),
            id_category: 1,
            id_country: countries[Math.floor(Math.random() * countries.length)],
            international_shipping: faker.datatype.boolean(),
            descriptions_products: {
              createMany: {
                data: [
                  {
                    id_language: 1,
                    description: `espanol- ${faker.commerce.productDescription()}`,
                  },
                  {
                    id_language: 2,
                    description: `english- ${faker.commerce.productDescription()}`,
                  },
                ],
              },
            },
            prices_products: {
              createMany: {
                data: [
                  {
                    id_currency: 1,
                    price: faker.commerce.price(),
                  },
                  {
                    id_currency: 2,
                    price: faker.commerce.price(),
                  },
                ],
              },
            },
          },
        });
      }

      console.log('Products created');
    } else {
      console.log('Default productcs already created');
    }
  } finally {
    await prisma.$disconnect();
  }
};

run();
